# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{slideshare}
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Saiku.es", "Russell Norris", "Andy Shen"]
  s.date = %q{2009-10-30}
  s.email = %q{andy@shenie.info}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "init.rb",
     "lib/slide_share/base.rb",
     "lib/slide_share/errors.rb",
     "lib/slide_share/slideshows.rb",
     "lib/slideshare.rb",
     "slideshare.gemspec",
     "spec/fixtures/config.yml",
     "spec/fixtures/config_missing_api_key.yml",
     "spec/fixtures/config_missing_shared_secret.yml",
     "spec/fixtures/delete_slideshow.xml",
     "spec/fixtures/edit_slideshow.xml",
     "spec/fixtures/error_failed_auth.xml",
     "spec/fixtures/error_not_found.xml",
     "spec/fixtures/error_permissions.xml",
     "spec/fixtures/get_slideshow.xml",
     "spec/fixtures/get_slideshow_detailed.xml",
     "spec/fixtures/sample.txt",
     "spec/fixtures/upload_slideshow.xml",
     "spec/slide_share/base_spec.rb",
     "spec/slide_share/slideshows_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/shenie/slideshare}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby interface for SlideShare API}
  s.test_files = [
    "spec/slide_share/base_spec.rb",
     "spec/slide_share/slideshows_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0.4.3"])
      s.add_runtime_dependency(%q<curb>, [">= 0.1.4"])
    else
      s.add_dependency(%q<httparty>, [">= 0.4.3"])
      s.add_dependency(%q<curb>, [">= 0.1.4"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0.4.3"])
    s.add_dependency(%q<curb>, [">= 0.1.4"])
  end
end

